# https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/macos/
variables:
  DEFAULT_NODE_VERSION: "12.x"


pool:
  vmImage: "macOS-10.15"


parameters:
- name: testJobs
  type: object
  default:
  - iosVersion: 12
    xcodeVersion: 10
    iosDeviceName: iPhone 6
    vmImage: macOS-10.14
  - iosVersion: 12.4
    xcodeVersion: 10.3
    iosDeviceName: iPhone X
    vmImage: macOS-10.14
  - iosVersion: 13.2
    xcodeVersion: 11.2
    iosDeviceName: iPhone 11
    vmImage: macOS-10.15
  - iosVersion: 13.7
    xcodeVersion: 11.7
    iosDeviceName: iPhone 11
    vmImage: macOS-10.15
  - iosVersion: 14
    xcodeVersion: 12
    iosDeviceName: iPhone 11
    vmImage: macOS-10.15


stages:
- stage: Unit_Test
  jobs:
  - ${{ each job in parameters.testJobs }}:
    - template: ./azure-templates/base_unit_test_job.yml
      parameters:
        name: Xcode_${{ replace(job.xcodeVersion, '.', '_') }}_iOS_${{ replace(job.iosVersion, '.', '_') }}
        xcodeVersion: ${{ job.xcodeVersion }}
        vmImage: ${{ job.vmImage }}

- stage: Integration_Test
  jobs:
  - ${{ each job in parameters.testJobs }}:
    - template: ./azure-templates/base_integration_test_job.yml
      parameters:
        name: Xcode_${{ replace(job.xcodeVersion, '.', '_') }}_iOS_${{ replace(job.iosVersion, '.', '_') }}
        iosVersion: ${{ job.iosVersion }}
        xcodeVersion: ${{ job.xcodeVersion }}
        iosDeviceName: ${{ job.iosDeviceName }}
        vmImage: ${{ job.vmImage }}
