parameters:
    name: ''
    vmImage: ''
    xcodeVersion: ''


jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      XCODE_VERSION: ${{ parameters.xcodeVersion }}
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: "$(DEFAULT_NODE_VERSION)"
    - script: ls /Applications
      displayName: List Apps
    - script: sudo xcode-select --switch "/Applications/Xcode_$(XCODE_VERSION).app/Contents/Developer"
      displayName: Prepare Env
    - script: xcrun simctl list
      displayName: List Simulators
    - script: npm install
      displayName: Install Package From NPM
    - script: npm test
