name: Functional Tests

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:

    # https://github.com/actions/runner-images/tree/main/images/macos
    strategy:
      matrix:
        include:
        - xcodeVersion: '14.3.1'
          iosVersion: '16.4'
          deviceName: 'iPhone 14'
          platform: macos-13
        - xcodeVersion: '15.4'
          iosVersion: '17.5'
          deviceName: 'iPhone 15'
          platform: macos-14
        - xcodeVersion: '16.4'
          iosVersion: '18.5'
          deviceName: 'iPhone 16'
          platform: macos-15
      fail-fast: false

    env:
      CI: true
      _FORCE_LOGS: 1
      MOBILE_OS_VERSION: ${{ matrix.iosVersion }}
      MOBILE_DEVICE_NAME: ${{ matrix.deviceName }}
      XCODE_VERSION: ${{ matrix.xcodeVersion }}
    # https://github.com/actions/runner-images/tree/main/images/macos
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: lts/*
        check-latest: true
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "${{ matrix.xcodeVersion }}"
    - run: |
        brew update
        brew tap wix/brew
        brew install applesimutils
        xcrun simctl list devices available
      name: Install Utilities
    - run: npm install
      name: Install dev dependencies
    - run: npm run e2e-test
      name: Run e2e tests on Xcode@${{ matrix.xcodeVersion }}
